app = "acervo-worker"
primary_region = "lax"

[build]
  dockerfile = "../Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  worker = "python worker/worker.py"

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 6
  processes = ["worker"]

[[vm]]
  memory = '16gb'
  cpu_kind = 'shared'
  cpus = 8
  memory_mb = 16384
